CREATE TABLE IF NOT EXISTS tblAccessRights (zzz int);
ALTER TABLE `tblAccessRights` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblAccessRights` ADD COLUMN IF NOT EXISTS `category` varchar(255) DEFAULT NULL;
ALTER TABLE `tblAccessRights` ADD COLUMN IF NOT EXISTS `name` varchar(255) NOT NULL;
ALTER TABLE `tblAccessRights` ADD COLUMN IF NOT EXISTS `desc` varchar(255) NOT NULL;
ALTER TABLE `tblAccessRights` ADD COLUMN IF NOT EXISTS `requireRights` varchar(255) DEFAULT NULL;
ALTER TABLE `tblAccessRights` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`name` ON `tblAccessRights`;
CREATE UNIQUE INDEX `name` ON `tblAccessRights` (`name`);
CREATE TABLE IF NOT EXISTS tblCompany (zzz int);
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `type` int(11) NOT NULL DEFAULT 2;
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `name` varchar(255) NOT NULL;
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `qName` varchar(255) DEFAULT NULL;
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `description` text NOT NULL;
ALTER TABLE `tblCompany` ADD COLUMN IF NOT EXISTS `invCode` char(10) DEFAULT NULL;
ALTER TABLE `tblCompany` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`fullName` ON `tblCompany`;
CREATE UNIQUE INDEX `fullName` ON `tblCompany` (`name`);
DROP INDEX IF EXISTS`invCode` ON `tblCompany`;
CREATE UNIQUE INDEX `invCode` ON `tblCompany` (`invCode`);
DROP INDEX IF EXISTS`type` ON `tblCompany`;
CREATE INDEX `type` ON `tblCompany` (`type`);
CREATE TABLE IF NOT EXISTS tblConfigRefTypes (zzz int);
ALTER TABLE `tblConfigRefTypes` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblConfigRefTypes` ADD COLUMN IF NOT EXISTS `module` varchar(255) DEFAULT NULL;
ALTER TABLE `tblConfigRefTypes` ADD COLUMN IF NOT EXISTS `ref_table` varchar(255) DEFAULT NULL;
ALTER TABLE `tblConfigRefTypes` ADD COLUMN IF NOT EXISTS `desc` varchar(255) DEFAULT NULL;
ALTER TABLE `tblConfigRefTypes` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`module` ON `tblConfigRefTypes`;
CREATE INDEX `module` ON `tblConfigRefTypes` (`module`(191));
CREATE TABLE IF NOT EXISTS tblUidRegistry (zzz int);
ALTER TABLE `tblUidRegistry` ADD COLUMN IF NOT EXISTS `uid` int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblUidRegistry` ADD COLUMN IF NOT EXISTS `module` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUidRegistry` ADD COLUMN IF NOT EXISTS `class` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUidRegistry` ADD COLUMN IF NOT EXISTS `ref_id` int(11) DEFAULT NULL;
ALTER TABLE `tblUidRegistry` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`module` ON `tblUidRegistry`;
CREATE UNIQUE INDEX `module` ON `tblUidRegistry` (`module`,`class`,`ref_id`);
CREATE TABLE IF NOT EXISTS tblGroupRightsLink (zzz int);
ALTER TABLE `tblGroupRightsLink` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblGroupRightsLink` ADD COLUMN IF NOT EXISTS `groupId` int(11) NOT NULL;
ALTER TABLE `tblGroupRightsLink` ADD COLUMN IF NOT EXISTS `module` varchar(255) NOT NULL DEFAULT 'core';
ALTER TABLE `tblGroupRightsLink` ADD COLUMN IF NOT EXISTS `rule` varchar(255) NOT NULL;
ALTER TABLE `tblGroupRightsLink` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`groupId_2` ON `tblGroupRightsLink`;
CREATE UNIQUE INDEX `groupId_2` ON `tblGroupRightsLink` (`groupId`,`rule`,`module`);
DROP INDEX IF EXISTS`groupId` ON `tblGroupRightsLink`;
CREATE INDEX `groupId` ON `tblGroupRightsLink` (`groupId`);
DROP INDEX IF EXISTS`rule` ON `tblGroupRightsLink`;
CREATE INDEX `rule` ON `tblGroupRightsLink` (`rule`);
DROP INDEX IF EXISTS`module` ON `tblGroupRightsLink`;
CREATE INDEX `module` ON `tblGroupRightsLink` (`module`);
CREATE TABLE IF NOT EXISTS tblModules (zzz int);
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `modName` varchar(128) DEFAULT NULL;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `features` varchar(128) DEFAULT NULL;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `isAliasFor` varchar(255) DEFAULT NULL;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `modPriority` int(11) NOT NULL DEFAULT 10;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `modVersion` varchar(50) DEFAULT NULL;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `modDesc` varchar(255) DEFAULT NULL;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `installDate` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblModules` ADD COLUMN IF NOT EXISTS `updateDate` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblModules` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`modName` ON `tblModules`;
CREATE UNIQUE INDEX `modName` ON `tblModules` (`modName`);
DROP INDEX IF EXISTS`features` ON `tblModules`;
CREATE INDEX `features` ON `tblModules` (`features`);
CREATE TABLE IF NOT EXISTS tblSessions (zzz int);
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `id` char(40) NOT NULL;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `startIP` int(11) unsigned DEFAULT NULL;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `currentIP` int(11) unsigned DEFAULT NULL;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `agent` varchar(255) DEFAULT NULL;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `userId` int(11) NOT NULL;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `lastActivity` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `type` char(10) DEFAULT 'web';
ALTER TABLE `tblSessions` ADD COLUMN IF NOT EXISTS `isClosed` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `tblSessions` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`userId` ON `tblSessions`;
CREATE INDEX `userId` ON `tblSessions` (`userId`);
DROP INDEX IF EXISTS`lastActivity` ON `tblSessions`;
CREATE INDEX `lastActivity` ON `tblSessions` (`lastActivity`);
DROP INDEX IF EXISTS`type` ON `tblSessions`;
CREATE INDEX `type` ON `tblSessions` (`type`);
DROP INDEX IF EXISTS`isClosed` ON `tblSessions`;
CREATE INDEX `isClosed` ON `tblSessions` (`isClosed`);
CREATE TABLE IF NOT EXISTS tblSettings (zzz int);
ALTER TABLE `tblSettings` ADD COLUMN IF NOT EXISTS `module` varchar(128) NOT NULL;
ALTER TABLE `tblSettings` ADD COLUMN IF NOT EXISTS `key` varchar(128) NOT NULL;
ALTER TABLE `tblSettings` ADD COLUMN IF NOT EXISTS `value` varchar(255) NOT NULL;
ALTER TABLE `tblSettings` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`module` ON `tblSettings`;
CREATE UNIQUE INDEX `module` ON `tblSettings` (`module`,`key`);
CREATE TABLE IF NOT EXISTS tblUserGroupLink (zzz int);
ALTER TABLE `tblUserGroupLink` ADD COLUMN IF NOT EXISTS `userId` int(11) NOT NULL;
ALTER TABLE `tblUserGroupLink` ADD COLUMN IF NOT EXISTS `groupId` int(11) NOT NULL;
ALTER TABLE `tblUserGroupLink` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`userId_2` ON `tblUserGroupLink`;
CREATE UNIQUE INDEX `userId_2` ON `tblUserGroupLink` (`userId`,`groupId`);
DROP INDEX IF EXISTS`userId` ON `tblUserGroupLink`;
CREATE INDEX `userId` ON `tblUserGroupLink` (`userId`);
DROP INDEX IF EXISTS`groupId` ON `tblUserGroupLink`;
CREATE INDEX `groupId` ON `tblUserGroupLink` (`groupId`);
CREATE TABLE IF NOT EXISTS tblUserGroups (zzz int);
ALTER TABLE `tblUserGroups` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblUserGroups` ADD COLUMN IF NOT EXISTS `name` varchar(255) NOT NULL;
ALTER TABLE `tblUserGroups` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`name` ON `tblUserGroups`;
CREATE INDEX `name` ON `tblUserGroups` (`name`);
CREATE TABLE IF NOT EXISTS tblUsers (zzz int);
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `login` varchar(255) NOT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `invCode` char(10) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `companyId` int(11) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `authType` char(50) DEFAULT 'internal';
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `authRefId` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `offlineAuthCtr` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `fullName` varchar(255) NOT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `firstName` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `middleName` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `lastName` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `eMail` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `uiTheme` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `secret` varchar(255) DEFAULT NULL;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `active` int(11) NOT NULL DEFAULT 1;
ALTER TABLE `tblUsers` ADD COLUMN IF NOT EXISTS `deleted` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `tblUsers` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`invCode` ON `tblUsers`;
CREATE UNIQUE INDEX `invCode` ON `tblUsers` (`invCode`);
DROP INDEX IF EXISTS`login` ON `tblUsers`;
CREATE INDEX `login` ON `tblUsers` (`login`(191));
DROP INDEX IF EXISTS`authType` ON `tblUsers`;
CREATE INDEX `authType` ON `tblUsers` (`authType`);
DROP INDEX IF EXISTS`authRefId` ON `tblUsers`;
CREATE INDEX `authRefId` ON `tblUsers` (`authRefId`(191));
DROP INDEX IF EXISTS`active` ON `tblUsers`;
CREATE INDEX `active` ON `tblUsers` (`active`);
DROP INDEX IF EXISTS`deleted` ON `tblUsers`;
CREATE INDEX `deleted` ON `tblUsers` (`deleted`);
CREATE TABLE IF NOT EXISTS tblLogs (zzz int);
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `timestamp` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `userId` int(11) NOT NULL;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `source` varchar(255) NOT NULL;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `message` text NOT NULL;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `severity` int(11) NOT NULL DEFAULT 2;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `subjClass` varchar(255) DEFAULT NULL;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `subjId` int(11) unsigned DEFAULT NULL;
ALTER TABLE `tblLogs` ADD COLUMN IF NOT EXISTS `addFields` text DEFAULT NULL;
ALTER TABLE `tblLogs` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`timestamp` ON `tblLogs`;
CREATE INDEX `timestamp` ON `tblLogs` (`timestamp`);
DROP INDEX IF EXISTS`userId` ON `tblLogs`;
CREATE INDEX `userId` ON `tblLogs` (`userId`);
DROP INDEX IF EXISTS`source` ON `tblLogs`;
CREATE INDEX `source` ON `tblLogs` (`source`);
DROP INDEX IF EXISTS`severity` ON `tblLogs`;
CREATE INDEX `severity` ON `tblLogs` (`severity`);
CREATE TABLE IF NOT EXISTS tblMetadata (zzz int);
ALTER TABLE `tblMetadata` ADD COLUMN IF NOT EXISTS `module` varchar(128) NOT NULL;
ALTER TABLE `tblMetadata` ADD COLUMN IF NOT EXISTS `key` varchar(128) NOT NULL;
ALTER TABLE `tblMetadata` ADD COLUMN IF NOT EXISTS `value` varchar(255) NOT NULL;
ALTER TABLE `tblMetadata` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`module` ON `tblMetadata`;
CREATE UNIQUE INDEX `module` ON `tblMetadata` (`module`,`key`);
CREATE TABLE IF NOT EXISTS tblFiles (zzz int);
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `uid` char(22) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `ownerId` int(11) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `aclRule` varchar(255) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `filename` varchar(512) NOT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `createStamp` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `size` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `type` varchar(255) NOT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `ext` varchar(255) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `hash` char(64) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `expireIn` int(11) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `deleted` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `aliasForId` int(11) DEFAULT NULL;
ALTER TABLE `tblFiles` ADD COLUMN IF NOT EXISTS `altTypes` text DEFAULT NULL;
ALTER TABLE `tblFiles` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`uid` ON `tblFiles`;
CREATE UNIQUE INDEX `uid` ON `tblFiles` (`uid`);
CREATE TABLE IF NOT EXISTS tblMailAccounts (zzz int);
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `address` varchar(255) NOT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `module` varchar(255) DEFAULT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxServer` varchar(255) DEFAULT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxProto` varchar(255) DEFAULT 'imap';
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxSSL` int(11) NOT NULL DEFAULT 1;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxPort` int(11) NOT NULL DEFAULT 993;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxFolder` varchar(255) DEFAULT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `rxArchiveFolder` varchar(255) DEFAULT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `txServer` varchar(255) DEFAULT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `txProto` varchar(255) NOT NULL DEFAULT 'smtp';
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `txSSL` int(11) NOT NULL DEFAULT 1;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `txPort` int(11) NOT NULL DEFAULT 465;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `login` varchar(255) NOT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `password` text NOT NULL;
ALTER TABLE `tblMailAccounts` ADD COLUMN IF NOT EXISTS `default` int(11) DEFAULT 0;
ALTER TABLE `tblMailAccounts` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`address_2` ON `tblMailAccounts`;
CREATE UNIQUE INDEX `address_2` ON `tblMailAccounts` (`address`);
DROP INDEX IF EXISTS`address` ON `tblMailAccounts`;
CREATE INDEX `address` ON `tblMailAccounts` (`address`);
CREATE TABLE IF NOT EXISTS tblMailMessages (zzz int);
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `accountId` int(11) NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `messageId` varchar(1024) NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `mailFrom` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `rcptTo` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `cc` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `bcc` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `direction` char(2) NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `subject` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `date` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `references` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `inReplyTo` text DEFAULT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `bodyHTML` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `bodyPLAIN` text NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `attachments` varchar(512) NOT NULL;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `dateEntry` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblMailMessages` ADD COLUMN IF NOT EXISTS `fromRobot` tinyint(1) DEFAULT 0;
ALTER TABLE `tblMailMessages` DROP COLUMN IF EXISTS zzz;
CREATE TABLE IF NOT EXISTS tblAuthTickets (zzz int);
ALTER TABLE `tblAuthTickets` ADD COLUMN IF NOT EXISTS `uid` char(16) NOT NULL;
ALTER TABLE `tblAuthTickets` ADD COLUMN IF NOT EXISTS `payload` text DEFAULT NULL;
ALTER TABLE `tblAuthTickets` ADD COLUMN IF NOT EXISTS `dateEntry` datetime NOT NULL DEFAULT current_timestamp;
ALTER TABLE `tblAuthTickets` ADD COLUMN IF NOT EXISTS `dateExpire` datetime DEFAULT NULL;
ALTER TABLE `tblAuthTickets` DROP COLUMN IF EXISTS zzz;
DROP INDEX IF EXISTS`dateEntry` ON `tblAuthTickets`;
CREATE INDEX `dateEntry` ON `tblAuthTickets` (`dateEntry`);
